[project]
name = "learn-pyspark"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipython>=9.3.0",
    "jupyterlab>=4.4.4",
    "pandas>=2.3.0",
    "pyspark==3.5.5",
    "requests>=2.32.4",
]
